# Trace of a Matrix

If A is a $n \times n$ square matrix. Then, trace of matrix $A_{n \times n}$ is defined as,
$$tr(A) = \sum_{i=1}^n a_{ii} = a_{11} + a_{22} + a_{33} + \dots + a_{nn}$$
where, $a_{ij}$ represent individual elements of the matrices A, B, and C respectively.

## Code

In [1]:
from numpy import array, random

In [2]:
# Code for calculating trace of a matrix
def matrix_trace(A):

    # Checking if the matrix is a square matrix
    if not A.shape[0] == A.shape[1]:
        raise ValueError("Trace of a matrix can only be calculated for a square matrix!")
    
    # Intialising variable `trace` to store the trace of the matrix
    trace = 0

    # Calculating the trace of the matrix
    for i in range(A.shape[0]):
        trace += A[i][i]

    return trace

## Examples

### $$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$$

In [3]:
# Declaring a matrix `A`
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

# Calculating the trace of the matrix
matrix_trace(A)

15

### Trace of a randomly generated matrix

In [4]:
# Generating a random matrix `A`
A = random.randint(1, 100, (3, 3))

In [5]:
A

array([[71, 93, 75],
       [71, 78, 15],
       [61, 94, 41]])

In [6]:
# Calculating the trace of the randomly generated matrix
matrix_trace(A)

190

## Trace of AB = Trace of BA

For any two square matrices A and B, $tr(AB) = tr(BA)$ 

#### Importing the code for matrix multiplication

In [7]:
from numpy import array, zeros

# Code for performing matrix multiplication
def matrix_multiply(A, B):
    
    # Checking if matrix multiplication is possible 
    if not A.shape[1] == B.shape[0]:
        raise ValueError("Matrix multiplication not possible!")
  
    # Decalring an empty matrix to store the result
    C = zeros((A.shape[0], B.shape[1]))

    # Performing matrix multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                C[i][j] += (A[i][k] * B[k][j])

    return C

### $tr(AB) = tr(BA)$ using two randomly generated matrices

In [8]:
# Generating two random matrices `A` and `B`
A = random.randint(1, 10, (3, 3))
B = random.randint(1, 10, (3, 3))

In [9]:
A

array([[4, 6, 8],
       [1, 7, 5],
       [2, 6, 5]])

In [10]:
B

array([[2, 7, 7],
       [3, 6, 6],
       [6, 8, 3]])

In [11]:
matrix_trace(matrix_multiply(A, B))

228.0

In [12]:
matrix_trace(matrix_multiply(B, A))

228.0