# Matrix Multilpication

If $A$ is a $m \times n$ matrix and $B$ is a $n \times p$ matrix. Then, matrix product $C_{m \times p} = A_{m \times n} \cdot B_{n \times p}$ is defined as,
$$c_{ij} = \sum_{k=1}^n a_{ik} \cdot b_{kj}$$
where, $a_{ij}$, $b_{ij}$, $c_{ij}$ represent individual elements of the matrices $A$, $B$, and $C$ respectively.

## Code

In [1]:
from numpy import array, zeros, random


In [2]:
# Code for performing matrix multiplication
def matrix_multiply(A, B):

    # Checking if matrix multiplication is possible
    if not A.shape[1] == B.shape[0]:
        raise ValueError("Matrix multiplication not possible!")

    # Decalring an empty matrix to store the result
    C = zeros((A.shape[0], B.shape[1]))

    # Performing matrix multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                C[i][j] += (A[i][k] * B[k][j])

    return C


## Examples

### $$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} \times \begin{bmatrix} 9 & 8 & 7 \\ 6 & 5 & 4 \\ 3 & 2 & 1 \end{bmatrix}$$

In [3]:
# Declaring two matrices `A` and `B`
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

B = array([[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]])

# Performing matrix multipliaction
matrix_multiply(A, B)


array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

### $$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} \times \begin{bmatrix} 9 & 8 \\ 6 & 5 \\ 3 & 2 \end{bmatrix}$$

In [4]:
# Declaring two non square matrices `A` and `B`
A = array([[1, 2, 3],
           [4, 5, 6]])

B = array([[9, 8],
           [6, 5],
           [3, 2]])

# Performing matrix multipliaction between two non square matrices
matrix_multiply(A, B)


array([[30., 24.],
       [84., 69.]])

### Matrix multiplication using two randomly generated matrices

In [5]:
# Generating two random matrices `A` and `B`
A = random.randint(1, 100, (3, 3))
B = random.randint(1, 100, (3, 3))


In [6]:
A


array([[91, 99, 98],
       [50, 82, 56],
       [98, 77, 92]])

In [7]:
B


array([[95, 30, 68],
       [87, 37, 67],
       [37, 72, 72]])

In [8]:
# Performing matrix multipliaction between two random matrices
matrix_multiply(A, B)


array([[20884., 13449., 19877.],
       [13956.,  8566., 12926.],
       [19413., 12413., 18447.]])