# Matrix Multilpication

If $A$ is a $m \times n$ matrix and $B$ is a $n \times p$ matrix. Then, matrix product $C_{m \times p} = A_{m \times n} \cdot B_{n \times p}$ is defined as,
$$c_{ij} = \sum_{k=1}^n a_{ik} + b_{kj}$$
where, $a_{ij}$, $b_{ij}$, $c_{ij}$ represent individual elements of the matrices $A$, $B$, and $C$ respectively.

In [1]:
from numpy import array, zeros

# Code for performing matrix multiplication
def matrix_multiply(A, B):
    
    # Checking if matrix multiplication is possible 
    if not A.shape[1] == B.shape[0]:
        raise ValueError("Matrix multiplication not possible!")
  
    # Decalring an empty matrix to store the result
    C = zeros((A.shape[0], B.shape[1]))

    # Performing matrix multiplication
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                C[i][j] += (A[i][k] * B[k][j])

    return C

In [2]:
# Declaring two matrices `A` and `B`
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

B = array([[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]])

# Performing matrix multipliaction 
matrix_multiply(A, B)

array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

In [3]:
# Declaring two non square matrices `A` and `B`
A = array([[1, 2, 3],
           [4, 5, 6]])

B = array([[9, 8],
           [6, 5],
           [3, 2]])

# Performing matrix multipliaction between two non square matrices
matrix_multiply(A, B)

array([[30., 24.],
       [84., 69.]])

In [4]:
from numpy import random

# Generating two random matrices `A` and `B`
A = random.randint(1, 100, (3, 3))
B = random.randint(1, 100, (3, 3))

In [5]:
A

array([[ 7, 97, 61],
       [36, 10, 66],
       [63, 84, 92]])

In [6]:
B

array([[78, 37,  7],
       [96, 38, 61],
       [61, 34, 68]])

In [7]:
# Performing matrix multipliaction between two random matrices
matrix_multiply(A, B)

array([[13579.,  6019., 10114.],
       [ 7794.,  3956.,  5350.],
       [18590.,  8651., 11821.]])